# Generated by Django 2.2.3 on 2019-07-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='endereco',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='name',
        ),
    ]
