# Generated by Django 2.2.3 on 2019-07-08 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0002_auto_20190705_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='name',
            new_name='nome',
        ),
    ]
