# Generated by Django 2.2.3 on 2019-07-08 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0003_auto_20190708_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='nome',
            new_name='name',
        ),
    ]
