# Generated by Django 2.2.3 on 2019-07-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0006_auto_20190708_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image',
            field=models.ImageField(default='baseline-check_circle_outline.csv', upload_to=' pic_folder/'),
        ),
    ]
