# Generated by Django 2.2.3 on 2019-07-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demanda', '0007_produto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='status',
            field=models.IntegerField(choices=[(1, 'Verdadeiro'), (2, 'Falso')], default=1),
        ),
    ]
